const fs = require('fs');
const path = require('path');

// Read from Vercel environment variables (or fall back to empty)
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

const content = `// Auto-generated by Vercel during build
window.SITE_CONFIG = {
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}'
};
`;

const targetPath = path.join(__dirname, 'assets', 'js', 'site-config.js');

// Ensure the directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

// Write the file
fs.writeFileSync(targetPath, content, 'utf8');
console.log('Successfully generated assets/js/site-config.js from Vercel environment variables.');
